# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b132800142e4e72d0a2b84b3123fe4d9256315f0975c978f9bf1989c528163209c6aba03de118a60abd730ef16ac1ab7e2ad35b660b78d95f500d5b1698879b4

test:
  secret_key_base: 6ce07840a566f4d8ac61596b36d24cd436314b7346d3e4276ea466e85467c3c6e6fa7ff82b067ea71a6b352aa9b7dc02a2f983eadadbe8db73a8838d1bff6a20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
